// Generated by CoffeeScript 1.3.3
(function() {
  var DiaryBody, DiaryBodyHtml;

  DiaryBody = $('.diary_body');

  DiaryBodyHtml = require("markdown").markdown.toHTML(DiaryBody);

  console.log(DiaryBodyHtml);

}).call(this);
