// Generated by CoffeeScript 1.3.3
(function() {

  $('.diary_body, .comment-body').each(function() {
    var BodyHtml, Converter, TargetText;
    TargetText = $(this).text().replace(/^\s+?([^\s]+)/g, "$1").replace(/\s+$/g, '').replace(/([^\n])\n([^\n])/g, "$1  \n$2").replace(/(^|\s)(https?:\/\/[a-zA-Z0-9\.\-_~#!%\?&\/]+?)(\s|$)/g, '$1<a href="$2">$2</a>$3');
    Converter = new Showdown.converter;
    BodyHtml = Converter.makeHtml(TargetText);
    return $(this).attr({
      "class": $(this).attr('class') + ' parsed'
    }).html(BodyHtml);
  });

}).call(this);
